### ISSUE TITLE
Returning a null value throws an exception

### ISSUE THREAD

**Issue by dallonf** [Netflix/falcor-router#120] opened 2015-08-21 15:56 UTC
If you return a null value like this:

```{path: ['hello'], value: null}```

The Router will throw an error:

```
TypeError: Cannot read property '$type' of null
    at pathValueMerge (C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\src\cache\pathValueMerge.js:22:29)
    at C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\src\run\mergeCacheAndGatherRefsAndInvalidations.js:37:29
    at Array.forEach (native)
    at mergeCacheAndGatherRefsAndInvalidations (C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\src\run\mergeCacheAndGatherRefsAndInvalidations.js:24:16)
    at C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\src\run\recurseMatchAndExecute.js:73:45
    at C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\node_modules\rx\dist\rx.js:4924:20
    at C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\node_modules\rx\dist\rx.js:4785:51
    at tryCatcher (C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\node_modules\rx\dist\rx.js:567:29)
    at InnerObserver.onNext (C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\node_modules\rx\dist\rx.js:4806:43)
    at InnerObserver.tryCatcher (C:\Users\DallonF\devroot\nuve-web\node_modules\falcor-router\node_modules\rx\dist\rx.js:567:29)
```

I expect this has to do with JavaScript's `typeof null == 'object'` shenanigans. I could probably fix this, just wanted to record it in case somebody can get to it before I can.

**Comment by jhusain** [comment] 2015-08-21 19:21
@michaelbpaulson can you take a look at this?

**Comment by sdesai** [comment] 2015-08-21 19:34
This may be fixed by the PR for: https://github.com/Netflix/falcor/issues/460

**Comment by sdesai** [comment] 2015-08-21 21:51
Just looked at the strack trace - has a different root cause. Added a (pending) test for it, with the PR above, and will look into a fix.

**Closed** 2015-08-21 22:07 UTC

**Comment by jhusain** [comment] 2015-08-21 23:52
@michaelbpaulson Can we push this to NPM?

JH

**Comment by michaelbpaulson** [comment] 2015-08-22 00:34
Well, we really need a way to track this via change logs.  When we release we just have a new version with no reasoning for why the new version is needed.  But ill release it.  We should strongly consider getting changelists before any more active dev is done.

**Comment by michaelbpaulson** [comment] 2015-08-22 00:37
v0.2.9 pushed to github / npm.
